SETH/A_WEB/urls.py
from django.urls import path, re_path
from .views import *
from django.views.generic.base import TemplateView 
from django.contrib.auth import views as auth 
from User.views import *


app_name = 'a_web'

urlpatterns = [
    path('', dashboard, name='dashboard'), 
    path('dashboard/', dashboard, name='dashboard'), 
    path('history/', history, name='history'), 
    path('makecert/', choose_cert, name='makecert'), 
    path('find_user_c', find_user_c_cert, name='find_user_c'), 
    path('find_user_c_any', find_user_c_any, name='find_user_c_any'), 
    path('makecertun/', make_cert, name='makecertun'),
    path('cuser/', register_c, name='cuser'), # new
    # path('registered', register_c, name='regist_c_registered'), 
    path('not_registered', register_c, name='regist_c_notregistered'), 
    path('register_face', register_face, name="register_face"),
    path('login/', auser_login, name="login"),
    path('logout/', auser_logout, name ='auser_logout'), 
    path('process_c_registration/', process_c_registration, name ='process_c_registration'), 
    re_path(r'^file/(?P<file>.+)/$', test_frontend, name="test_frontend"),
    
] 

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SETH/SETH/urls.py
from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import path, include
from django.urls.conf import re_path
from django.conf import settings
from .views import *
from User import views as UserViews
from django.views.generic.base import TemplateView 
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', lambda r:  redirect('a_web:dashboard'), name='home'), # new
    path('a_web/', include('A_WEB.urls')),
    path('b_web/', include('B_WEB.urls')),
    path('c_api/', include('C_API.urls')),
    
    path('authenticate', UserViews.common_user_login, name='authenticate'),
    path('qr_code/', include('qr_code.urls', namespace="qr_code")),
    re_path(r'^staticfiles/(?P<path>.+)/$', static_serve, name="test_frontend"),


    # path('face_core/', include('face_core.urls')),

    # path("user/", include('User.urls', namespace='user') ),
    # path('logout/', auth.LogoutView.as_view(template_name ='index.html'), name ='logout'), 


]  

SETH/templates/base.html
{% load static %}
<html>

    <head>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">        <!--adding css-->
        <link rel="stylesheet" href="{% static 'base.css'%}"> 
        <style>
            {% block css %}
            {% endblock css %}
        </style>
        <title> TreeHacks </title>
    </head>
    <body>
        {% comment %} navbar here {% endcomment %}
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#" style = 'font-size: 35px;'>HealthCare</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" style = 'font-size: 20px;'>
                    <li class="nav-item">
                    {% comment %} <a class="nav-link" aria-current="page" href="{% url 'forum' %}"> QnA Forum </a> {% endcomment %}
                    </li>
                    <li class="nav-item">
                      {% comment %} <a class="nav-link" href="{% url 'patient:about_us' %}"> Our services </a> {% endcomment %}
                    </li>
                    <li class="nav-item">
                    {% comment %} <a class="nav-link" href="{% url 'contact_us' %}"> Contact Us </a> {% endcomment %}
                    </li>
                </ul>

                <ul class="navbar-nav ml-auto mb-2 mb-lg-0" style = 'font-size: 20px;'>
                  {% if user.is_authenticated %}
                  <li class="nav-item">
                    {% comment %} <a class="nav-link" aria-current="page" href="{% url 'logout' %}"> Logout </a> {% endcomment %}
                  </li>
                  {% else %}
                  <li class="nav-item">
                    {% comment %} <a class="nav-link" aria-current="page" href="{% url 'login' %}"> Login </a> {% endcomment %}
                  </li>
                  {% endif %}
              </ul>

                </div>
            </div>
         </nav>

        {% block body %}
        {% endblock body %}

    </body>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
    {% block js %}
    {% endblock js %}
</html>

SETH/templates/cert.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<button onclick="{% url 'a_web:cert' %}">Make Certificate</button>
<br>

<button onclick="{% url 'a_web:past_cert' %}">Make Certificate</button>
<br>

<button onclick="window.location = '{% url 'a_web:regist_c' %}'">Make Certificate</button>
<br>

{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

SETH/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% comment %} <button onclick="{% url 'a_web:cert' %}">Make Certificate</button>
<br>

<button onclick="{% url 'a_web:past_cert' %}">Make Certificate</button>
<br> {% endcomment %}

<button onclick="window.location = '{% url 'a_web:regist_c' %}'">Make Certificate</button>
<br>

{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

SETH/templates/new_window.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>

<script>
    window.open('{{url}}', '_blank', 'location=yes,height=570,width=520,scrollbars=yes,status=yes');
</script>
</html>

SETH/templates/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

      
    

</body>

<script>
        window.addEventListener('load', function () {
        // window.location = "{{url}}";
        // window.location.replace("{{url}}");
        document.location = "{{url}}";
      });
</script>
</html>

SETH/templates/regist_c.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<button onclick="window.location = '{% url 'a_web:regist_c_registered' %}'">The user has been registered with phone</button>
<br>

<button onclick="window.location = '{% url 'a_web:regist_c_notregistered' %}'">The user has NOT been registered with phone</button>


{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

SETH/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{ test }}
</body>
</html>

SETH/templates/vid_base_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face Registration</title>
</head>
<body>
  <body>
    <h1>Hello {{ name }} please register your face</h1>
    <h2>Please turn your face to left and to right SLOWLY. And hit done button after that</h2>
    <img src="{% url 'face_core:add_face_src' %}">
    <form method="GET" action="">
      <input type="submit" value="Done"/>
    </form>
  </body>
    
</body>
</html>

SETH/templates/vid_base_auth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Face Registration</title>
</head>
<body>
  <body>
    <h1>Register your face</h1>
    <h2>Please turn your face to left and to right SLOWLY</h2>
    <img src="{% url 'face_core:auth_face_src' %}">
  </body>
    
</body>
</html>